---
postgresql_version: 17
postgresql_data_directory: /var/lib/pgsql/{{ postgresql_version }}/data
postgresql_log_directory: /var/log/pgsql
postgresql_user: postgres
postgresql_group: postgres
postgresql_password: postgres
postgresql_auth_method: "{{ (postgresql_version is version('10', '>=')) | ternary('scram-sha-256', 'md5') }}"
postgresql_initdb_options: -E UTF8 {% if postgresql_version is version('9.3', '>=') %}-k{% endif %} --locale=C
postgresql_port: 5432
postgresql_ssl_enabled: true
postgresql_primary_server: "{{ groups.postgresql.0 }}"
postgresql_home_directory: /var/lib/pgsql
postgresql_replication_role: replication
postgresql_replication_password: replication
